# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef0e4cf48f8bbfdee5ee1a4e2836afe3d25e449e499d7d43b2ae6cb3e7afa2066d14891ff8f0042a7722f099c862d22c8335def9e7b5a5ba92e5100294d3a879

test:
  secret_key_base: d692be0f265e29bed1c2e298bbf545b24be4a382ff46e6002539eb7221c4441d7c159fc53149489f820124e7dd22ce20a211b044b7c463140bd53410d1d09400

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
